sonar.projectKey=studymate-lab1
sonar.projectName=StudyMate — ТИОПО ЛР №1
sonar.sourceEncoding=UTF-8

sonar.sources=app/src/main,data/src/main,domain/src/main

sonar.tests=data/src/test

sonar.java.binaries=app/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes,data/build/intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes,domain/build/classes/kotlin/main

sonar.coverage.jacoco.xmlReportPaths=data/build/reports/jacoco/lab/jacoco.xml

sonar.exclusions=**/build/**,**/src/androidTest/**
