#!/usr/bin/env python3
"""Mark failed/missing/skipped CI stages in the combined GitHub Pages Allure report.

Real Python test cases and Gradle JUnit XML remain untouched. This writes just
one synthetic stage summary for each failed/skipped job instead of a fake entry
for every unexecuted test, and handles lost/missing artifacts explicitly.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / 'lab2' / 'reports'

STAGES = {
    'unit-python': 'CI_STATUS_UNIT_PYTHON',
    'unit-android': 'CI_STATUS_UNIT_ANDROID',
    'integration': 'CI_STATUS_INTEGRATION',
    'android-device': 'CI_STATUS_ANDROID_DEVICE',
    'e2e': 'CI_STATUS_E2E',
}


def main() -> None:
    outcomes = []
    for stage, variable in STAGES.items():
        if variable not in os.environ:
            continue   # Normal CI has no physical-device stage.
        result = os.environ[variable]
        marker = REPORTS / 'ci-stage-results' / f'{stage}.txt'
        artifact_ok = marker.is_file()
        outcome = marker.read_text().strip() if artifact_ok else 'missing artifact'
        if result == 'success' and artifact_ok and outcome == 'success':
            continue
        if result == 'skipped':
            status, message = 'skipped', f'GitHub Actions skipped {stage} because prerequisite jobs did not succeed'
        else:
            status = 'failed'
            message = (f'GitHub Actions job {stage}: {result}. '
                       f'Result artifact: {outcome}. Check the job log for details.')
        # A stage is a logical job, not one test. Preserve individual testcase
        # records already generated by pytest/JUnit; add a single status result.
        subprocess.run([
            sys.executable, str(ROOT / 'lab2/scripts/report_stage.py'),
            stage, status, message, '--reports', str(REPORTS),
        ], check=True)
        outcomes.append((stage, result, artifact_ok))
    print(f'Aggregated {len(outcomes)} failed/missing/skipped stage statuses')
    for stage, result, artifact_ok in outcomes:
        print(f'  {stage}: {result}; artifact={artifact_ok}')


if __name__ == '__main__':
    main()
