FROM eclipse-temurin:11-jdk AS jdk11
FROM ghcr.io/cirruslabs/android-sdk:36

COPY --from=jdk11 \
    /opt/java/openjdk \
    /usr/lib/jvm/temurin-11

ENV JDK11_HOME=/usr/lib/jvm/temurin-11

ENV GRADLE_OPTS="\
    -Dorg.gradle.java.installations.paths=/usr/lib/jvm/temurin-11 \
    -Dorg.gradle.java.installations.auto-download=false"

RUN /usr/lib/jvm/temurin-11/bin/java -version \
    && /usr/lib/jvm/temurin-11/bin/javac -version \
    && yes | sdkmanager --install "platforms;android-36.1"

WORKDIR /workspace/mobile-app

CMD ["bash", "-lc", "\
    chmod +x ./gradlew && \
    ./gradlew --no-daemon :data:labCoverage \
"]
